---

- hosts: webservers
  become: yes
  gather_facts: yes

  pre_tasks:
    - shell: echo 'hello to dfsc'

  roles:
    - LEMP

  tasks:
    - include: tasks/sites-dfsc.yml

  post_tasks:
    - shell: echo 'cheers'

  handlers:
   - name: restart php5-fpm
     service: name=php5-fpm state=restarted

   - name: restart nginx
     service: name=nginx state=restarted
   